import re, colorsys, sys
import os
P=os.path.join(os.path.dirname(__file__),'..','app','globals.css')
START='/* ==== LIGHT THEME (generated by scripts/light-theme.py) ==== */'
END='/* ==== END LIGHT THEME ==== */'
src=open(P).read()
if START in src: src=src[:src.index(START)].rstrip()+'\n'
ROOT=':root[data-theme="light"]'
COLOR_RE=re.compile(r'#[0-9a-fA-F]{3,8}\b|rgba?\([^)]*\)')
PROPS={'color':'text','fill':'text','stroke':'text','caret-color':'text','text-decoration-color':'text',
 'background':'bg','background-color':'bg',
 'border':'border','border-top':'border','border-right':'border','border-bottom':'border','border-left':'border','border-color':'border',
 'border-top-color':'border','border-bottom-color':'border','border-left-color':'border','border-right-color':'border','outline':'border','outline-color':'border'}
KEEP_SCOPES=('.hero','.ticker','.gym-visual','.image-label','.final-cta')
def parse(c):
    c=c.lstrip('#') if c.startswith('#') else c
    if c.startswith('rgb'):
        n=[float(x) for x in re.findall(r'[\d.]+',c)]
        return n[0]/255,n[1]/255,n[2]/255,(n[3] if len(n)>3 else 1)
    if len(c) in (3,4): c=''.join(ch*2 for ch in c)
    r,g,b=(int(c[i:i+2],16)/255 for i in (0,2,4)); a=int(c[6:8],16)/255 if len(c)==8 else 1
    return r,g,b,a
def fmt(r,g,b,a):
    h='#%02x%02x%02x'%tuple(round(max(0,min(1,x))*255) for x in (r,g,b))
    return h if a>=0.999 else h+'%02x'%round(a*255)
def tf(col, role):
    r,g,b,a=parse(col)
    h,l,s=colorsys.rgb_to_hls(r,g,b)
    bright_green = s>0.5 and 0.45<l<0.9 and 0.15<h<0.35
    if a<0.999:
        if a==0: return col
        if l>0.5: return fmt(0,0,0,a*0.9)   # white overlays -> black overlays
        return col                          # dark scrims/backdrops stay
    if role=='text':
        if l<0.35: return col               # dark text sits on green/light surfaces
        if bright_green: nl=0.3; s=min(s,0.75)
        else: nl=max(0.08,min(0.45,1.02-l))
    elif role=='bg':
        if l>0.72 or bright_green: return col
        nl=max(0.93,min(0.995,0.955+(l-0.07)*0.35)); s=min(s,0.45)
    else:
        if bright_green: return col
        if l<0.5: nl=max(0.72,min(0.9,0.9-(l-0.15)*0.4)); s=min(s,0.4)
        else: nl=max(0.25,1.05-l)
    r,g,b=colorsys.hls_to_rgb(h,nl,s)
    return fmt(r,g,b,1)
def tval(v, role, keep):
    if keep or 'gradient' in v or 'url(' in v: return v
    v2=COLOR_RE.sub(lambda m: tf(m.group(0),role), v)
    if role=='text' and v.strip().startswith('var(--green)'): v2=v.replace('var(--green)','var(--green-ink)')
    return v2
def prefix(sel):
    out=[]
    for s in sel.split(','):
        s=s.strip()
        if not s or s.startswith(':root') or s.startswith('@'): return None
        if s=='html': out.append(ROOT)
        elif s.startswith('html'): out.append(ROOT+s[4:])
        else: out.append(ROOT+' '+s)
    return ','.join(out)
out=[]
i=0; n=len(src)
def walk(text, media):
    pos=0
    while True:
        m=re.search(r'[{}]',text[pos:])
        if not m: break
        j=pos+m.start()
        if text[j]=='}': pos=j+1; continue
        head=text[pos:j].strip()
        # find matching brace
        depth=1;k=j+1
        while depth and k<len(text):
            if text[k]=='{': depth+=1
            elif text[k]=='}': depth-=1
            k+=1
        body=text[j+1:k-1]
        head=re.sub(r'/\*.*?\*/','',head,flags=re.S).strip()
        if head.startswith('@media'): walk(body, head)
        elif head.startswith('@'): pass
        else:
            sel=prefix(head)
            if sel:
                keep=any(sc in head for sc in KEEP_SCOPES)
                decls=[]
                for d in re.sub(r'/\*.*?\*/','',body,flags=re.S).split(';'):
                    if ':' not in d: continue
                    p,v=d.split(':',1); p=p.strip().lower(); v=v.strip()
                    if p in PROPS and v: decls.append(f'{p}:{tval(v,PROPS[p],keep)}')
                if decls: out.append((media, f'{sel}{{{";".join(decls)}}}'))
        pos=k
walk(src,None)
lines=[START]
for media,rule in out: lines.append(f'{media}{{{rule}}}' if media else rule)
manual='''
:root[data-theme="light"]{--bg:#f4f4ef;--surface:#ffffff;--line:#dcddd5;--text:#141613;--muted:#5a5f59;--green-ink:#3f6b0a;color-scheme:light}
:root[data-theme="light"] .logo .logo-on-dark{display:none}
:root[data-theme="light"] .logo .logo-on-light{display:block}
:root[data-theme="light"] .hero,:root[data-theme="light"] .gym-visual{--text:#f4f4ef;--muted:#cfd2cb;--line:#ffffff40;color:#f4f4ef}
:root[data-theme="light"] .final-cta{--text:#10130c;--muted:#2c3a17}
:root[data-theme="light"] .hero .btn.outline{color:#f4f4ef;border-color:#ffffffa6;background:transparent}
:root[data-theme="light"] .hero .btn.outline:hover{background:#ffffff26}
:root[data-theme="light"] .modal::backdrop,:root[data-theme="light"] .mobile-drawer[data-open="true"]::backdrop{background:#10120e66}
:root[data-theme="light"] .form-message.error,:root[data-theme="light"] .door-status.error{color:#b42318}
:root[data-theme="light"] .door-status{color:var(--green-ink)}
:root[data-theme="light"] .app-tile,:root[data-theme="light"] .plan,:root[data-theme="light"] .history,:root[data-theme="light"] .app-row,:root[data-theme="light"] .app-form{box-shadow:0 1px 2px #0000000a,0 8px 24px -16px #00000026}
'''
lines.append(manual.strip()); lines.append(END)
open(P,'w').write(src+'\n'+'\n'.join(lines)+'\n')
print(len(out),'rules generated')
